apiVersion: v2
name: archive
description: A Helm chart for archive microservice
type: application
version: 1.0.0-SNAPSHOT
appVersion: "1.0.0-SNAPSHOT"

dependencies:
  - name: basic
    version: 1.0.0-SNAPSHOT
    condition: basicEnabled
    repository: "oci://ghcr.io/yuryklimchuk/prodms"

